services:
  server:
    build:
      context: .
      target: dev
      args:
        DATABASE_URL: mongodb://root:prisma@mongodb:27017/sesami-app?authSource=admin&directConnection=true
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      DATABASE_URL: mongodb://root:prisma@mongodb:27017/sesami-app?authSource=admin&directConnection=true
      PORT: 3000
      DEPLOYMENT_ENV: stage
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app

  mongodb:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      INIT_WAIT_SEC: 10
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/sesami-app --quiet
      interval: 10s
      timeout: 10s
      retries: 2
      start_period: 10s